name: Nightly Build

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Ubuntu suite'
        required: false
        default: 'plucky'
      flavor:
        description: 'Image flavor'
        required: false
        default: 'desktop'

jobs:
  build-rootfs:
    runs-on: ubuntu-22.04
    name: Build rootfs
    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: vars
        run: |
          source config/suites/${{ github.event.inputs.suite }}.sh
          echo "suite_version=$RELASE_VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools \
          squashfs-tools snapd

      - name: Build Rootfs
        run: sudo ./build.sh --suite=${{ github.event.inputs.suite }} --flavor=${{ github.event.inputs.flavor }} --rootfs-only --launchpad

      - name: Upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ steps.vars.outputs.suite_version }}-preinstalled-${{ github.event.inputs.flavor }}-arm64-rootfs
          path: ./build/ubuntu-${{ steps.vars.outputs.suite_version }}-preinstalled-${{ github.event.inputs.flavor }}-arm64.rootfs.tar.xz
          if-no-files-found: error
